apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: ebh53z2m5-java-quarkus-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/ebh53z2m5-java-quarkus-gitops